apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-example
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: go-k8s-example
          image: go-k8s-example:1.0
          ports:
            - containerPort: 8080