# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uploader
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: uploader
            image: alpine
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
          restartPolicy: OnFailure